### PR TITLE
Issue/1185

### PR DESCRIPTION
**Pull request by cklosowski**
Let's try this again @SDavisMedia. That should handle the fact that GF AJAXs in the form.

### CODE REVIEW

**Comment by SDavisMedia** [comment]
@cklosowski you wanna test this from staging (not sure that would even work)? Otherwise, I'm gonna adjust the base to `master` and merge.

**Comment by cklosowski** [comment]
@SDavisMedia we'd be able to test the initial trigger, but the last trigger has as different ID...can we add custom classes to fields or something so that I can trigger on those instead? That way we could test in staging, and not have to be so 'specific' with the selectors.

**Comment by SDavisMedia** [comment]
@cklosowski Nice. I've added the class `self-help-ga-trigger-start` to the start field and `self-help-ga-trigger-open-ticket` to the next button to start opening the support ticket. :+1:

**Comment by cklosowski** [comment]
@SDavisMedia ok my selectors are updated, let's get this on the staging site and we can try it out.

**Pull request merged**
